name: CI - FLASK App



on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
 build-test:
  runs-on: ubuntu-latest

  steps: 
   - name: Checkout repository
     uses: actions/checkout@v5


   - name: Set up Python
     uses: actions/setup-python@v5
     with:
      Python-version: "3.11"

   - name: Install dependencies
     run: |
      python -m pip install --upgrade pip
      pip installrequirements.txt
      pip install pytest pytest-cov

   - name: Run tests
     env:
      FLASK_ENV:testing
     run: pytest -v --maxfail =1 --disable-warnings --cov=app



     
